### PR TITLE
Use boost::multiprecision for 128-bit datatypes

### PR DESCRIPTION
**Pull request by raulbehl**
- This fixes compilation issues seen on pure 32-bit machines

### CODE REVIEW

**Comment by jrahmeh** [comment]
Thank you!

**Comment by jrahmeh** [comment]
Hi Raulbehl,
Thank you again for your contribution to swerv-ISS.  Recently, we have decided to change the license from GPL-3.0 to Apache-2.0 so that it matches our SweRV core licenses for consistency. Can you please confirm that we can use your contributions to swerve-ISS under Apache-2.0?

Thanks,
Joe

**Comment by jrahmeh** [comment]
Hi Raulbehl,

Following up on my earlier email regarding Swerv-ISS.  Please let me know if you are OK with your contributions been put under Apache-2.0 as we are looking to change the license to math that of our SweRV cores.

Thanks,

Joe

**Comment by raulbehl** [comment]
Hello @jrahmeh, 

Apologies for the late reply. I believe it should be OK.

**Comment by jrahmeh** [comment]
Thank you!

**Pull request merged**
