### PR TITLE
Minor Fixes

### PR DESCRIPTION
**Pull request by AmeyaVS**
* Fix `#include` statments to include C++ Standard library headers
  instead of `C` style headers.
* Fix `isnan` function is available only in `std` namespace, this fixes the
  compilation on multuple platforms.
* Fix `GNUmakefile` remove unused `boost_system` library dependency and cleanup
  `SRCS_C` variable for removed source file.

### CODE REVIEW

**Review by jrahmeh — APPROVED** [review]

**Comment by jrahmeh** [comment]
Thanks for the changes.

**Comment by jrahmeh** [comment]
Merged.

**Comment by jrahmeh** [comment]
Hi Ameya,
Thank you again for your contribution to swerv-ISS.  Recently, we have decided to change the license from GPL-3.0 to Apache-2.0 so that it matches our SweRV core licenses for consistency. Can you please confirm that we can use your contributions to swerve-ISS under Apache-2.0?
Thanks,
Joe Rahmeh

**Comment by jrahmeh** [comment]
Hi Ameya,

Following up on my earlier email regarding Swerv-ISS. Please let me know if you are OK with your contributions been put under Apache-2.0 as we are looking to change the license to match that of our SweRV cores.

Thanks,

Joe Rahmeh

**Comment by AmeyaVS** [comment]
Hello @jrahmeh,

Regarding the contribution relicensing from GPL-3.0 to Apache-2.0, I have no objection.

Also, I would like to bring to your notice that the changes in the pull request #12 and #13.
Were never ever properly attributed, even though the changes were manually integrated into the project.

Related Commits: [here](https://github.com/AmeyaVS/swerv-ISS/commit/6d101e50a249d79ab9350c198e0644ae88beff32) and [here](https://github.com/AmeyaVS/swerv-ISS/commit/34ac03258359d83cc2b9aaab6db31bf719b3c08a).

Regards,
Ameya Vikram Singh

**Comment by jrahmeh** [comment]
Ameya,

Thank you.  I am not sure how to attribute the change.  This is what I
wrote on github (visible to all):

The new scope for label l11 in the decoder has been accepted and is now
part of the code. Thank you.
I would prefer not to change the GNUmakefile as that will affect local
development. External user can always use "make BOOST_ROOT=x" where x is
the path to their boost installation.

If there is anything else I can do to give you credit, I will be more than
happy to do it.

Joe

**Pull request merged**
